version: "3.7"
services:
  pg:
    container_name: pg
    image: postgres
    environment:
      POSTGRES_USER: me
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      # - postgresql_node_db:/var/lib/postgresql/data
      - ./db:/var/lib/postgresql/data

  ns:
    container_name: ns
    build:
      context: ./node-server
    depends_on:
      - pg
    environment:
      DB_HOST: pg
    ports:
      - "3000:3000"
# volumes:
# postgresql_node_db:
